name: "Go"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: "${{ github.event.action != 'merge_group' }}"

jobs:
  build:
    name: "Build"
    uses: HyperaDev/actions/.github/workflows/go-build.yml@main
    with:
      go_version: "stable"
      lint_enabled: true
      vulncheck_enabled: true
